// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhqiPLeD0k83aROrnD861kRQXv_-AjYU',
    appId: '1:720003732552:web:f91203c999a013a08b747d',
    messagingSenderId: '720003732552',
    projectId: 'voyageflutter-3e173',
    authDomain: 'voyageflutter-3e173.firebaseapp.com',
    storageBucket: 'voyageflutter-3e173.appspot.com',
    measurementId: 'G-23RNCB8JHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQTlH951pIV4ipsYg3OsggXpQXqCQoFLk',
    appId: '1:720003732552:android:86c1cd8072c362f98b747d',
    messagingSenderId: '720003732552',
    projectId: 'voyageflutter-3e173',
    storageBucket: 'voyageflutter-3e173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9v6FhCr3AMx1H5VS7fPd0c8Exg4EpKQ',
    appId: '1:720003732552:ios:101ebf8ea97826c88b747d',
    messagingSenderId: '720003732552',
    projectId: 'voyageflutter-3e173',
    storageBucket: 'voyageflutter-3e173.appspot.com',
    iosBundleId: 'com.example.repository',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA9v6FhCr3AMx1H5VS7fPd0c8Exg4EpKQ',
    appId: '1:720003732552:ios:101ebf8ea97826c88b747d',
    messagingSenderId: '720003732552',
    projectId: 'voyageflutter-3e173',
    storageBucket: 'voyageflutter-3e173.appspot.com',
    iosBundleId: 'com.example.repository',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRhqiPLeD0k83aROrnD861kRQXv_-AjYU',
    appId: '1:720003732552:web:6167c9c08c0c5f6a8b747d',
    messagingSenderId: '720003732552',
    projectId: 'voyageflutter-3e173',
    authDomain: 'voyageflutter-3e173.firebaseapp.com',
    storageBucket: 'voyageflutter-3e173.appspot.com',
    measurementId: 'G-3HX9L6GNQE',
  );
}
